# Generated by Django 4.2 on 2023-04-27 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("report_date", models.DateField()),
                ("time_before_breakfast", models.TimeField()),
                (
                    "blood_before_breakfast",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("time_at_breakfast", models.TimeField()),
                ("breakfast_meal", models.CharField(max_length=100)),
                ("time_at_lunch", models.TimeField()),
                ("lunch_meal", models.CharField(max_length=100)),
                ("time_at_dinner", models.TimeField()),
                ("dinner_meal", models.CharField(max_length=100)),
                ("time_after_dinner", models.TimeField()),
                (
                    "blood_after_dinner",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
        ),
    ]
